name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Pobranie kodu
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Instalacja Pythona
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip' # Cache pip dependencies

    # 3. Instalacja zależności (Prod + Dev)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    # 4. Linting (Ruff)
    - name: Lint with Ruff
      run: |
        # Sprawdzamy folder app i tests. Wyjście niezerowe przy błędzie zatrzyma CI.
        ruff check app tests

    # 5. Testy (Pytest)
    - name: Run tests
      run: |
        # Dodajemy bieżący katalog do PYTHONPATH, żeby testy widziały 'app'
        export PYTHONPATH=$PYTHONPATH:.
        pytest -v
